/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.io.*;
import javax.swing.*;
import Classes.*;
import javax.swing.event.*;
/**
 *
 * @author Tom
 */
public class AddRemovePlayerForm extends javax.swing.JFrame {

    /**
     * Creates new form AddRemovePlayerForm
     */
    private TeamManager manager;
    public AddRemovePlayerForm() {
        initComponents();
    }
    public AddRemovePlayerForm(TeamManager Manager)
    {
        this.manager = Manager;
        initComponents();
        this.lstTeamName.addListSelectionListener(new ListSelectionListener()
                {
                    public void valueChanged(ListSelectionEvent Event)
                    {
                        JList Source = (JList) Event.getSource();
                        lstTeamNameItemSelected(Event);
                    }

           
                    
                });
        String[] Teams = ReadTeamsFile();  
        ReadPlayerFile(Teams);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTeamName = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPlayerName = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        btnRemovePlayer = new javax.swing.JButton();
        btnAddPlayer = new javax.swing.JButton();
        btnCloseForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstTeamName);

        jLabel1.setText("Teams");

        jScrollPane2.setViewportView(lstPlayerName);

        jLabel2.setText("Players");

        jLabel3.setText("Player Name");

        btnRemovePlayer.setText("Remove Player");
        btnRemovePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePlayerActionPerformed(evt);
            }
        });

        btnAddPlayer.setText("Add Player");
        btnAddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPlayerActionPerformed(evt);
            }
        });

        btnCloseForm.setText("Close Form");
        btnCloseForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddPlayer)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(btnRemovePlayer))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(btnCloseForm)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPlayer)
                    .addComponent(btnRemovePlayer))
                .addGap(18, 18, 18)
                .addComponent(btnCloseForm)
                .addGap(162, 162, 162))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPlayerActionPerformed
        try
        {
            int index = 0;
            System.out.println("Clicked");
            for (int i = 0; i < manager.GetTeams().size(); i++)
            {
                if(manager.GetTeams().get(i).getName().equals(this.lstTeamName.getSelectedValue().toString()))
                {
                    index = i;
                    manager.GetTeams().get(i).AddPlayer(new Player(this.txtPlayerName.getText()));
                    break;
                }
            }
                if(this.txtPlayerName.getText().equals(""))
                {
                    throw new Exception();
                }
                this.lstPlayerName.setListData(CreatePlayerList(this.lstTeamName.getSelectedValue().toString()));
                this.txtPlayerName.setText("");
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Please Select A Team Name");
        }
    }//GEN-LAST:event_btnAddPlayerActionPerformed

    private void btnRemovePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePlayerActionPerformed

            int index = 0;
            int TeamIndex = 0;
            for (int i = 0; i < manager.GetTeams().size(); i++)
            {
                 if(manager.GetTeams().get(i).getName().equals(this.lstTeamName.getSelectedValue().toString()))
                {
                    TeamIndex = i;
                    manager.GetTeams().get(i).AddPlayer(new Player(this.txtPlayerName.getText()));
                    break;
                }
            }
            for (int i = 0; i < manager.GetTeams().size(); i++)
            {
                if(manager.GetTeams().get(TeamIndex).GetPlayers().get(i).GetName().equals(this.lstPlayerName.getSelectedValue().toString()))
                {
                    index = i;
                    manager.GetTeams().get(TeamIndex).RemovePlayerByIndex(index);
                    break;
                }
            }
                this.lstPlayerName.setListData(CreatePlayerList(this.lstTeamName.getSelectedValue().toString()));
                this.txtPlayerName.setText("");
    }//GEN-LAST:event_btnRemovePlayerActionPerformed

    private void btnCloseFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseFormActionPerformed
        
        try
        {
            String[] TeamList = CreateTeamList();
            //String[] PlayerList = CreatePlayerList();
            File f = new File("Players.txt");
            FileWriter fw = new FileWriter(f,false);
            BufferedWriter br = new BufferedWriter(fw);
            for(int i = 0; i < TeamList.length; i++)
            {
                br.write(TeamList[i] + ",");
                String[] PlayerList = CreatePlayerList(TeamList[i]);
                for(int j = 0; j < PlayerList.length; j++)
                {
                    br.write(PlayerList[j] + ",");
                }
                br.write('\n');
               // manager.AddTeam(new Team(list[i]));
            }
            br.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "An Error occured while writing the teams to a file");
            ex.printStackTrace();
        }
        finally
        {
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_btnCloseFormActionPerformed
    
    private String[] CreateTeamList()
    {
        String[] names = new String[manager.GetTeams().size()];
        for(int i = 0; i < manager.GetTeams().size(); i++)
        {
            names[i] = manager.GetTeams().get(i).getName();
        }
        return names;
    } 
       
    private String[] CreatePlayerList(String TeamName)
    {
        Team T;
        int index = 0;
        String[] names = null;
        for (int i = 0; i < manager.GetTeams().size(); i++)
        {
            if(manager.GetTeams().get(i).getName().equals(TeamName))
            {
                index = i;
                names = new String[manager.GetTeams().get(index).GetPlayers().size()];
                for(int j = 0; j < manager.GetTeams().get(index).GetPlayers().size(); j++)
                {
                    names[j] = manager.GetTeams().get(index).GetPlayers().get(j).GetName();
                }
                break;
            }
        }
        if(manager.GetTeams().get(index).GetPlayers().isEmpty())
        {
            names[0] = "No Players";
            return names;
        } 
    
        return names;
    }
    
    private String[] ReadTeamsFile()
    {
        try
        {
            String ReadTeams;
            String[] Teams;
            File f = new File("Teams.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            ReadTeams = br.readLine();
            Teams = ReadTeams.split(",[ ]*");
             for(int i = 0; i < Teams.length; i++)
            {
                manager.AddTeam(new Team(Teams[i]));
            }
            this.lstTeamName.setListData(Teams);
            br.close();
            return Teams;
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "There Was an error while reading the team data file");
        }
        return null;
    }
    private void ReadPlayerFile(String[] Teams)
    {
        try
        {
            String ReadPlayers;
            String[] Players = null;
            File f = new File("Players.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            while((ReadPlayers = br.readLine()) != null)
            {
                Players = ReadPlayers.split(",[ ]*");
                for(int i = 0; i < Teams.length; i++)
                {
                    for(int j = 1; j < Players.length; j++)
                    {
                        manager.GetTeams().get(i).AddPlayer(new Player(Players[j]));
                    }
            }   
            }
            //this.lstPlayerName.setListData(Players);
            br.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "There Was an error while reading the team data file");
        }
    }
    private void lstTeamNameItemSelected(ListSelectionEvent Event) {
        String Selected = this.lstTeamName.getSelectedValue().toString();
        this.lstPlayerName.setListData(CreatePlayerList(Selected));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPlayer;
    private javax.swing.JButton btnCloseForm;
    private javax.swing.JButton btnRemovePlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstPlayerName;
    private javax.swing.JList lstTeamName;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables

}
