/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import Classes.*;
import java.io.*;
import javax.swing.*;
/**
 * This class manages the league table form 
 * @author Tom
 */
public class LeagueTableForm extends javax.swing.JFrame {

    /**
     * Default Constructor for LeagueTableForm
     */
    private TeamManager manager;
    public LeagueTableForm() {
        initComponents();
    }
     /**
     * Constructor for LeagueTableForm which takes a TeamManager so teams can be read from a file
     * @param Manager The team manager that will manage the teams
     */
    public LeagueTableForm(TeamManager Manager)
    {
         this.manager = Manager;
        initComponents();
        try
        {
            String ReadText;
            File f = new File("Scores.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            while((ReadText = br.readLine()) != null)
            {
                String replace = ReadText.replace(',', ' ');
                this.txtTable.setText(this.txtTable.getText() + replace + "\n");
            }
            br.close();
            
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(null, "An Error occured while reading the data from a file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTable = new javax.swing.JTextArea();
        btnCloseForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtTable.setColumns(20);
        txtTable.setRows(5);
        jScrollPane1.setViewportView(txtTable);

        btnCloseForm.setText("Close Form");
        btnCloseForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(btnCloseForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCloseForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called when the close form button is pressed so the form closes
     * @param evt The event listener for the close form button
     */
    private void btnCloseFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseFormActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnCloseFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseForm;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTable;
    // End of variables declaration//GEN-END:variables
}
